bboard/bboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

bboard/main/urls.py
from django.urls import path

from .views import (
    BBLoginView,
    BBLogoutView,
    PasswordEditView,
    ProfileDeleteView,
    ProfileEditView,
    RegisterDoneView,
    RegisterView,
    index,
    other_page,
    profile,
    rubric_bbs,
    user_activate,
)

app_name = "main"

urlpatterns = [
    path("", index, name="index"),
    path("<int:pk>/", rubric_bbs, name="rubric_bbs"),
    path("<str:page>/", other_page, name="other"),
    path("accounts/login/", BBLoginView.as_view(), name="login"),
    path("accounts/logout/", BBLogoutView.as_view(), name="logout"),
    path("accounts/profile/", profile, name="profile"),
    path(
        "accounts/profile/edit/",
        ProfileEditView.as_view(),
        name="profile_edit",
    ),
    path(
        "accounts/profile/delete/",
        ProfileDeleteView.as_view(),
        name="profile_delete",
    ),
    path(
        "accounts/password/edit/",
        PasswordEditView.as_view(),
        name="password_edit",
    ),
    path(
        "accounts/register/done/",
        RegisterDoneView.as_view(),
        name="register_done",
    ),
    path("accounts/register/", RegisterView.as_view(), name="register"),
    path("accounts/activate/<str:sign>/", user_activate, name="activate"),
]

bboard/main/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from .utilities import get_timestamp_path


class AdvUser(AbstractUser):
    is_activated = models.BooleanField(
        default=True, db_index=True, verbose_name="Прошел активацию?"
    )
    send_messages = models.BooleanField(
        default=True, verbose_name="Слать оповещения о новых комментариях?"
    )

    def delete(self, *args, **kwargs):
        for bb in self.bb_set.all():
            bb.delete()
        super().delete(*args, **kwargs)

    class Meta(AbstractUser.Meta):
        pass


class SuperRubricManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(super_rubric__isnull=True)


class SubRubricManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(super_rubric__isnull=False)


class Rubric(models.Model):
    name = models.CharField(
        max_length=20, unique=True, verbose_name="Название"
    )
    order = models.SmallIntegerField(
        default=0, db_index=True, verbose_name="Порядок"
    )
    super_rubric = models.ForeignKey(
        "SuperRubric",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        verbose_name="Надрубрика",
    )


class SuperRubric(Rubric):
    objects = SuperRubricManager()

    def __str__(self):
        return self.name

    class Meta:
        proxy = True
        ordering = ("order", "name")
        verbose_name = "Надрубрика"
        verbose_name_plural = "Надрубрики"


class SubRubric(Rubric):
    objects = SubRubricManager()

    def __str__(self):
        return "%s - %s" % (self.super_rubric.name, self.name)

    class Meta:
        proxy = True
        ordering = (
            "super_rubric__order",
            "super_rubric__name",
            "order",
            "name",
        )
        verbose_name = "Подрубрика"
        verbose_name_plural = "Подрубрики"


class Bb(models.Model):
    """Модель объявлений."""

    rubric = models.ForeignKey(
        SubRubric, on_delete=models.PROTECT, verbose_name="Рубрика"
    )
    title = models.CharField(max_length=40, verbose_name="Товар")
    content = models.TextField(verbose_name="Описание")
    price = models.FloatField(default=0, verbose_name="Цена")
    contacts = models.TextField(verbose_name="Контакты")
    image = models.ImageField(
        blank=True, upload_to=get_timestamp_path, verbose_name="Изображение"
    )
    author = models.ForeignKey(
        AdvUser, on_delete=models.CASCADE, verbose_name="Автор объявления"
    )
    is_active = models.BooleanField(
        default=True, db_index=True, verbose_name="Выводить в списке?"
    )
    created_at = models.DateTimeField(
        auto_now_add=True, db_index=True, verbose_name="Опубликовано"
    )

    def delete(self, *args, **kwargs):
        for ai in self.additionalimage_set.all():
            ai.delete()
        super().delete(*args, **kwargs)

    class Meta:
        verbose_name_plural = "Объявления"
        verbose_name = "Объявление"
        ordering = ["-created_at"]


class AdditionalImage(models.Model):
    """Модель дополнительных иллюстраций."""

    bb = models.ForeignKey(
        Bb, on_delete=models.CASCADE, verbose_name="Объявление"
    )
    image = models.ImageField(
        upload_to=get_timestamp_path, verbose_name="Изображение"
    )

    class Meta:
        verbose_name_plural = "Дополнительные иллюстрации"
        verbose_name = "Дополнительная иллюстрация"

bboard/main/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError

from .models import AdvUser, SubRubric, SuperRubric
from .signals import post_register


class ProfileEditForm(forms.ModelForm):
    """Форма редактирования профиля."""

    email = forms.EmailField(required=True, label="Адрес электронной почты")

    class Meta:
        model = AdvUser
        fields = (
            "username",
            "email",
            "first_name",
            "last_name",
            "send_messages",
        )


class RegisterForm(forms.ModelForm):
    email = forms.EmailField(required=True, label="Адрес электронной почты")
    password1 = forms.CharField(
        label="Пароль",
        widget=forms.PasswordInput,
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label="Пароль (повторно)",
        widget=forms.PasswordInput,
        help_text="Введите тот же самый пароль еще раз для проверки",
    )

    def clean_password1(self):
        password1 = self.cleaned_data["password1"]
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data["password1"]
        password2 = self.cleaned_data["password2"]
        if password1 and password2 and password1 != password2:
            errors = {
                "password2": ValidationError(
                    "Введенные пароли не совпадают", code="password_mismatch"
                )
            }
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        post_register.send(RegisterForm, instance=user)
        return user

    class Meta:
        model = AdvUser
        fields = (
            "username",
            "email",
            "password1",
            "password2",
            "first_name",
            "last_name",
            "send_messages",
        )


class SubRubricForm(forms.ModelForm):
    super_rubric = forms.ModelChoiceField(
        queryset=SuperRubric.objects.all(),
        empty_label=None,
        label="Надрубрика",
        required=True,
    )

    class Meta:
        model = SubRubric
        fields = "__all__"

bboard/main/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.signing import BadSignature
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .forms import ProfileEditForm, RegisterForm
from .models import AdvUser
from .utilities import signer


def index(request):
    return render(request, "main/index.html")


def other_page(request, page):
    try:
        template = get_template("main/" + page + ".html")
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


class BBLoginView(LoginView):
    """Класс-представление для входа пользователя."""

    template_name = "main/login.html"


class BBLogoutView(LogoutView):
    pass


@login_required
def profile(request):
    return render(request, "main/profile.html")


class ProfileEditView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    """Редактирование личных данных пользователя."""

    model = AdvUser
    template_name = "main/profile_edit.html"
    form_class = ProfileEditForm
    success_url = reverse_lazy("main:profile")
    success_message = "Данные пользователя изменены"

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class PasswordEditView(
    SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView
):
    template_name = "main/password_edit.html"
    success_url = reverse_lazy("main:profile")
    success_message = "Пароль пользователя изменен"


class RegisterView(CreateView):
    model = AdvUser
    template_name = "main/register.html"
    form_class = RegisterForm
    success_url = reverse_lazy("main:register_done")


class RegisterDoneView(TemplateView):
    template_name = "main/register_done.html"


def user_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, "main/activation_failed.html")
    user = get_object_or_404(AdvUser, username=username)
    if user.is_activated:
        template = "main/activation_done_earlier.html"
    else:
        template = "main/activation_done.html"
        user.is_active = True
        user.is_activated = True
        user.save()
    return render(request, template)


class ProfileDeleteView(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    model = AdvUser
    template_name = "main/profile_delete.html"
    success_url = reverse_lazy("main:index")
    success_message = "Пользователь удален"

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        logout(request)
        return super().post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


def rubric_bbs(request, pk):
    pass

bboard/main/templates/layout/base.html
{% load django_bootstrap5 %} {% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>{% block title %}Главная{% endblock %} - Доска объявлений</title>
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}" />
    {% bootstrap_javascript %}
</head>

<body class="container-fluid">
    <header class="mb-4">
        <h1 class="display-1 text-center">Объявления</h1>
    </header>
    <!-- Навигация -->
    <nav class="row navbar navbar-expand-md bg-light">
        <div class="col container">
            <a class="navbar-brand" href="{% url 'main:index' %}">Главная</a>
            <!-- Меню -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button> <!-- Кнопка бургер -->
            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                    <!-- Выпадающее меню -->
                    <div class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#">Профиль</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'main:profile' %}">Мои объявления</a>
                            <a class="dropdown-item" href="{% url 'main:profile_edit' %}">Изменить личные данные</a>
                            <a class="dropdown-item" href="{% url 'main:password_edit' %}">Изменить пароль</a>
                            <hr class="dropdown-divider" />
                            <form class="px-3" method="post" action="{% url 'main:logout' %}">
                                {% csrf_token %}
                                {% bootstrap_button 'Выйти' button_class='btn-danger' %}
                            </form>
                            <hr class="dropdown-divider" />
                            <a class="dropdown-item" href="{% url 'main:profile_delete' %}">Удалить</a>
                        </div>
                    </div> <!-- Выпадающее меню -->
                    {% else %}
                    <a class="nav-link" href="{% url 'main:register' %}">Регистрация</a>
                    <a class="nav-link" href="{% url 'main:login' %}">Вход</a>
                    {% endif %}
                </div>
            </div> <!-- Меню -->
        </div>
    </nav> <!-- Навигация -->
    <div class="row">
        <!-- Рубрики -->
        <nav class="col-md-auto nav flex-column bg-light">
            {% for rubric in rubrics %}
            {% ifchanged rubric.super_rubric.pk %}
            <span class="nav-link root">{{ rubric.super_rubric.name }}</span>
            {% endifchanged %}
            <a class="nav-link" href="{% url 'main:rubric_bbs' pk=rubric.pk %}">
                {{ rubric.name }}</a>
            {% endfor %}
            <a class="nav-link root" href="{% url 'main:other' page='about' %}">О сайте</a>
        </nav> <!-- Рубрики -->
        <main class="col py-2">
            {% bootstrap_messages %} {% block content %}{% endblock %}
        </main>
    </div>
    <footer class="mt-3">
        <p class="text-end fst-italic">&copy; читатели.</p>
    </footer>
</body>

</html>